@startuml Cinema

class Cinema {
    
    -nome: String
    -salas: Salas
    -ingresso: Ingresso
    -cliente: String
    +construct(salas, ingresso)
    +comprar_ingresso(ingresso)
    +registrar_cliente(cliente)
}

class Salas {

    -filme: string 
    -num_sala: Int 
    -poltrona: Int 
    +construct(num_sala, poltrona)
    +exibir_filme(filme)
}

class Filme {

    -titulo: String
    -duracao: Int 
    -categoria: String 

    +construct(titulo, duracao, categoria)

}

class Ingresso {

    -num_ingresso: Int 
    -num_sala: Int
    -titulo_filme: String
    -preco: Float
    -num_poltrona: Int
    +construct(num_ingresso, num_poltrona, num_sala, titulo_filme, preco)
}

class Pessoa {

    -nome: String 
    -data_nascimento: Date
    -endereco: String  
    +construct(nome, data_nascimento, endereco)
}

class Pessoa_Fisisca {

    -cpf: Int
    +construct(pessoa, cpf)
    +validar_cpf(cpf)
}

class Pessoa_Juridica {
    
    -cnpj: Int 
    +construct(pessoa, cnpj)
    +validar_cnpj(cnpj)
}


Cinema <-- Salas
Cinema <-- Ingresso 
Salas <|-- Filme   
Cinema <-- Pessoa 
Pessoa <|-- Pessoa_Fisisca
Pessoa <|-- Pessoa_Juridica




@enduml 